### ISSUE TITLE
Implementation of Kanban Board Template for Group Capstone

### ISSUE THREAD

**Issue by the-faizmohammad** [the-faizmohammad/Capstone-API-based-webapp#21]
### Objective: 
The objective of this project is to establish a comprehensive Kanban Board template within the JavaScript Group Capstone Repository.

### Team Members: 
- Mr. Faiz Mohammad (@the-faizmohammad)
- Mr. Md. Arafat Hossain (@HossainAraf)

### Project Overview:
This initiative involves the creation and configuration of a highly functional Kanban Board template meticulously tailored to address the specific requirements of the JavaScript Group Capstone Repository. The Kanban Board will serve as a powerful visual tool to streamline project management, enhance collaboration, and facilitate efficient task tracking and progression.

Furthermore, this project is aligned with the principles of agile project management, enabling the team to effectively organize tasks, monitor progress, and allocate resources to optimize productivity and ensure the successful realization of the Group Capstone objectives.

#### Project Kanban Board Link:
For detailed insights into the project's progress and task management, kindly refer to the following link: [Project Kanban Board](https://github.com/the-faizmohammad/Capstone-API-based-webapp/projects/4)

Your active engagement and support in this endeavor are greatly appreciated.

Best regards,
Faiz

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @the-faizmohammad and @HossainAraf,

Good job so far!
✔️ Kanban columns are complete
✔️ Tasks are complete
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] Kindly choose who would be Students A and B and assign your tasks. They should look like so if properly assigned.

  ![andre-assigned](https://github.com/the-faizmohammad/Capstone-API-based-webapp/assets/36542986/d087a305-f040-4974-aeef-6432a3a6a9fa)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by the-faizmohammad** [comment]
Thank you for the feedback, I have made the required changes.

**Comment by Davidosky007** [comment]
Hi @the-faizmohammad @HossainAraf 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* All team members' information provided 👍 
* Link to Kanban board works 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by the-faizmohammad** [comment]
Thank you so much for your great feedback 🤗
